nombre = input("Ingresa tu nombre: ")
edad = input("Ingresa tu edad: ")
ciudad = input("Ingresa tu ciudad de residencia: ")
comida_favorita = input("Ingresa tu comida favorita: ")
pasatiempo = input("Ingresa tu pasatiempo favorito: ")
sueno = input("Ingresa tu mayor sueño: ")
mascota = input("Ingresa el nombre de tu mascota: ")

print("\n--- HISTORIA DEL PROTAGONISTA ---")
print("¡Hola, " + nombre + "! Tienes " + edad + " años y vives en " + ciudad + ".")
print(nombre + " es una persona que disfruta mucho de " + comida_favorita + " y le encanta " + pasatiempo + ".")
print("Además, siempre comparte momentos especiales con su mascota llamada " + mascota + ".")
print("Desde pequeño, " + nombre + " ha tenido un gran sueño: " + sueno + ".")
print("Un día, caminando por las calles de " + ciudad + ", decidió que era momento de luchar por ese sueño.")
print("Con esfuerzo, entusiasmo y valentía, " + nombre + " demostró que la edad de " + edad + " años es perfecta para comenzar una gran aventura.")
